# Generated by Django 3.1.2 on 2022-03-25 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FilesApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestresultmodel',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='contestresultmodel',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.contestmodel', verbose_name='Конкурс'),
        ),
        migrations.AddField(
            model_name='contestresultmodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilesApp.filemodel', verbose_name='Файл для распознавания'),
        ),
        migrations.AddField(
            model_name='contestresultconfigmodel',
            name='contest_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.contestresultmodel', verbose_name='Результаты конкурса'),
        ),
        migrations.AddField(
            model_name='contestmodel',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
